apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;

        location /app1 {
            proxy_pass http://app1-service:80;
        }

        location /app2 {
            proxy_pass http://app2-service:80;
        }
    }
